[package]
name = "glfw-sys"
version = "0.1.0"
authors = ["Per Lönn Wege <per.loenn.wege@gmail.com>"]
links = "glfw"
build = "build.rs"
license = "MIT"
repository = "https://github.com/perlw/glfw-rs"
description = "Native bindings to the glfw library"

[lib]
name = "glfw_sys"
path = "lib.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1.26"
